### ISSUE TITLE
EndpointsExtractor.bb Problem

### ISSUE THREAD

**Issue by ozguralp** [ghsec/BBProfiles#1]
Hey,
I noticed that you deleted this profile, could it be related with this problem: https://github.com/wagiro/BurpBounty/issues/60 if not, I just wondered that whether you encountered this problem before.

**Comment by ghsec** [comment]
Hello @ozguralp . No.  I delete because the same profile is on Burp Bounty repository.
https://github.com/wagiro/BurpBounty/blob/master/profiles/EndpointsExtractor.bb
this is a same nd you can use it

**Comment by ozguralp** [comment]
Gotcha, thanks for the info!

**Comment by ghsec** [comment]
@ozguralp you are welcome
